export const seedProducts = [
  {
    name: 'Apple iPhone 17 Pro',
    slug: 'iphone-17-pro',
    brand: 'Apple',
    category: 'smartphones',
    description: 'The next generation flagship iPhone featuring a revolutionary titanium unibody design, A19 Pro Neural Chip, standard-setting Super Retina XDR ProMotion display, and a breakthrough 48MP triple-lens camera system with 6x optical zoom.',
    sellerName: 'Balaji Infocom',
    soldCount: 70,
    cashbackBadge: '1% Cashback',
    downPayment: 20235,
    rating: 4.2,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1000&q=80',
    ],
    highlights: [
      'Storage: 256 GB',
      'Color: Silver',
      'Front Camera: 18MP',
      'Front Camera Features: 18MP front cam with autofocus, Center Stage, Night mode, HDR 5, portraits, Animoji, 4K stabilized video, spatial audio, and dual capture features.',
      'Rear Camera: 48MP + 48MP + 48MP',
      'Rear Camera Features: 48MP Fusion system with 4 lenses, 8x zoom, up to 40x digital, ProRAW, Night mode, Smart HDR 5, macro, spatial photos, and advanced stabilization.',
      'Screen Size: 6.3 inch',
      'Screen Resolution: 2622 × 1206 Pixels',
    ],
    specifications: [
      { label: 'Storage', value: '256 GB' },
      { label: 'Color', value: 'Silver' },
      { label: 'Front Camera', value: '18MP' },
      { label: 'Rear Camera', value: '48MP + 48MP + 48MP' },
      { label: 'Screen Size', value: '6.3 inch' },
      { label: 'Screen Resolution', value: '2622 × 1206 Pixels' },
      { label: 'Processor', value: 'Apple A19 Pro (3nm)' },
      { label: 'OS', value: 'iOS 18' },
    ],
    includedItems: [
      'iPhone 17 Pro with iOS 18',
      'USB-C Charge Cable (1m)',
      'Documentation & SIM Eject Tool',
    ],
    deliveryInfo: 'Dispatch in less than 48 hours and delivery in 3-7 working days after dispatch',
    variants: [
      {
        id: 'iphone-17-pro-256gb-silver',
        name: '256GB / Silver',
        color: 'Silver',
        colorCode: '#E3E4E5',
        storage: '256 GB',
        price: 127400,
        mrp: 134900,
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80',
        stock: 18,
      },
      {
        id: 'iphone-17-pro-512gb-black',
        name: '512GB / Space Black',
        color: 'Space Black',
        colorCode: '#1C1C1E',
        storage: '512 GB',
        price: 147400,
        mrp: 154900,
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=80',
        stock: 12,
      },
    ],
    emiPlans: [
      {
        id: 'emi-iphone-3m',
        tenure: 3,
        monthlyAmount: 42467,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 127401,
        isRecommended: false,
      },
      {
        id: 'emi-iphone-6m',
        tenure: 6,
        monthlyAmount: 21233,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 127398,
        isRecommended: false,
      },
      {
        id: 'emi-iphone-12m',
        tenure: 12,
        monthlyAmount: 10617,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 127404,
        isRecommended: false,
      },
      {
        id: 'emi-iphone-24m',
        tenure: 24,
        monthlyAmount: 5308,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 127392,
        isRecommended: true,
      },
      {
        id: 'emi-iphone-36m',
        tenure: 36,
        monthlyAmount: 4297,
        interestRate: 10.5,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 154692,
        isRecommended: false,
      },
      {
        id: 'emi-iphone-48m',
        tenure: 48,
        monthlyAmount: 3385,
        interestRate: 10.5,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 162480,
        isRecommended: false,
      },
      {
        id: 'emi-iphone-60m',
        tenure: 60,
        monthlyAmount: 2842,
        interestRate: 10.5,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 170520,
        isRecommended: false,
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        author: 'Anuradha Doshi',
        location: 'Mumbai',
        rating: 5,
        date: '4 months ago',
        isVerified: true,
        reviewVariant: 'Storage: 256 GB, Color: Silver',
        comment: 'This is a great support by team for this product is fantastic thanks',
        imageAttachment: null,
      },
      {
        id: 'rev-2',
        author: 'Jayalaxmi Arigela',
        location: 'tarnaka',
        rating: 5,
        date: '4 months ago',
        isVerified: true,
        reviewVariant: 'Storage: 256 GB, Color: Cosmic Orange',
        comment: 'Good',
        imageAttachment: null,
      },
      {
        id: 'rev-3',
        author: 'Ajad Ali',
        location: 'Unnao',
        rating: 5,
        date: '5 months ago',
        isVerified: true,
        reviewVariant: 'Storage: 256 GB, Color: Silver',
        comment: 'Excellent',
        imageAttachment: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=300&q=80',
      },
    ],
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    brand: 'Samsung',
    category: 'smartphones',
    description: 'Unleash unprecedented productivity and creativity with Galaxy AI. Features a titanium frame, built-in S Pen, 200MP camera system with quad telephoto, and ultra-bright 2600 nits QHD+ Dynamic AMOLED 2X display.',
    sellerName: 'Balaji Infocom',
    soldCount: 85,
    cashbackBadge: '1% Cashback',
    downPayment: 21500,
    rating: 4.3,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=1000&q=80',
    ],
    highlights: [
      'Storage: 256 GB',
      'Color: Titanium Gray',
      'Front Camera: 12MP Dual Pixel',
      'Rear Camera: 200MP + 50MP + 10MP + 12MP',
      'Screen Size: 6.8 inch',
      'Screen Resolution: 3120 × 1440 Pixels (QHD+)',
    ],
    specifications: [
      { label: 'Storage', value: '256 GB' },
      { label: 'Color', value: 'Titanium Gray' },
      { label: 'Front Camera', value: '12MP' },
      { label: 'Rear Camera', value: '200MP + 50MP + 10MP + 12MP' },
      { label: 'Screen Size', value: '6.8 inch' },
      { label: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
      { label: 'OS', value: 'Android 14 (One UI 6.1)' },
    ],
    includedItems: [
      'Samsung Galaxy S24 Ultra',
      'Integrated S Pen',
      'Type-C Data Cable',
      'Ejection Pin',
    ],
    deliveryInfo: 'Dispatch in less than 48 hours and delivery in 3-7 working days after dispatch',
    variants: [
      {
        id: 'samsung-s24u-256gb-titanium-gray',
        name: '256GB / Titanium Gray',
        color: 'Titanium Gray',
        colorCode: '#686B73',
        storage: '256 GB',
        price: 129999,
        mrp: 144999,
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=80',
        stock: 22,
      },
      {
        id: 'samsung-s24u-512gb-titanium-black',
        name: '512GB / Titanium Black',
        color: 'Titanium Black',
        colorCode: '#2B2C2E',
        storage: '512 GB',
        price: 139999,
        mrp: 159999,
        image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=80',
        stock: 14,
      },
    ],
    emiPlans: [
      {
        id: 'emi-samsung-3m',
        tenure: 3,
        monthlyAmount: 43333,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 129999,
        isRecommended: false,
      },
      {
        id: 'emi-samsung-6m',
        tenure: 6,
        monthlyAmount: 21666,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 129996,
        isRecommended: false,
      },
      {
        id: 'emi-samsung-12m',
        tenure: 12,
        monthlyAmount: 10833,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 129996,
        isRecommended: false,
      },
      {
        id: 'emi-samsung-24m',
        tenure: 24,
        monthlyAmount: 5416,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 129984,
        isRecommended: true,
      },
      {
        id: 'emi-samsung-36m',
        tenure: 36,
        monthlyAmount: 4385,
        interestRate: 10.5,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 157860,
        isRecommended: false,
      },
    ],
    reviews: [
      {
        id: 'rev-s24-1',
        author: 'Rohan Sharma',
        location: 'Delhi',
        rating: 5,
        date: '2 months ago',
        isVerified: true,
        reviewVariant: 'Storage: 256 GB, Color: Titanium Gray',
        comment: 'Unbelievable camera and S Pen performance! EMI process was super smooth.',
        imageAttachment: null,
      },
    ],
  },
  {
    name: 'Google Pixel 9 Pro',
    slug: 'google-pixel-9-pro',
    brand: 'Google',
    category: 'smartphones',
    description: 'Engineered by Google to put Gemini AI at your fingertips. Features the custom Tensor G4 chip, an award-winning Triple Rear Camera System with Super Res Zoom, matte glass back, and 24+ hour battery life.',
    sellerName: 'Balaji Infocom',
    soldCount: 52,
    cashbackBadge: '1% Cashback',
    downPayment: 18000,
    rating: 4.4,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=1000&q=80',
    ],
    highlights: [
      'Storage: 128 GB',
      'Color: Obsidian',
      'Front Camera: 42MP',
      'Rear Camera: 50MP + 48MP + 48MP',
      'Screen Size: 6.3 inch',
      'Screen Resolution: 1280 × 2856 Pixels',
    ],
    specifications: [
      { label: 'Storage', value: '128 GB' },
      { label: 'Color', value: 'Obsidian' },
      { label: 'Front Camera', value: '42MP' },
      { label: 'Rear Camera', value: '50MP + 48MP + 48MP' },
      { label: 'Screen Size', value: '6.3 inch' },
      { label: 'Processor', value: 'Google Tensor G4' },
      { label: 'OS', value: 'Android 15' },
    ],
    includedItems: [
      'Google Pixel 9 Pro',
      '1m USB-C Cable',
      'Quick Switch Adapter & SIM tool',
    ],
    deliveryInfo: 'Dispatch in less than 48 hours and delivery in 3-7 working days after dispatch',
    variants: [
      {
        id: 'pixel-9-pro-128gb-obsidian',
        name: '128GB / Obsidian',
        color: 'Obsidian',
        colorCode: '#1F2022',
        storage: '128 GB',
        price: 109999,
        mrp: 119999,
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=80',
        stock: 25,
      },
      {
        id: 'pixel-9-pro-256gb-porcelain',
        name: '256GB / Porcelain',
        color: 'Porcelain',
        colorCode: '#F4F3EF',
        storage: '256 GB',
        price: 119999,
        mrp: 129999,
        image: 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&w=1000&q=80',
        stock: 18,
      },
    ],
    emiPlans: [
      {
        id: 'emi-pixel-3m',
        tenure: 3,
        monthlyAmount: 36666,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 109998,
        isRecommended: false,
      },
      {
        id: 'emi-pixel-6m',
        tenure: 6,
        monthlyAmount: 18333,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 109998,
        isRecommended: false,
      },
      {
        id: 'emi-pixel-12m',
        tenure: 12,
        monthlyAmount: 9166,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 109992,
        isRecommended: false,
      },
      {
        id: 'emi-pixel-24m',
        tenure: 24,
        monthlyAmount: 4583,
        interestRate: 0,
        cashback: 7500,
        processingFee: 0,
        totalAmount: 109992,
        isRecommended: true,
      },
    ],
    reviews: [
      {
        id: 'rev-px-1',
        author: 'Kavita Verma',
        location: 'Bengaluru',
        rating: 5,
        date: '3 months ago',
        isVerified: true,
        reviewVariant: 'Storage: 128 GB, Color: Obsidian',
        comment: 'Pure Android bliss and Gemini AI features are fantastic!',
        imageAttachment: null,
      },
    ],
  },
];
